### ISSUE TITLE
Hello Mr Girsh Nanda, is there anyway I can contact you in person ?

### ISSUE THREAD

**Issue by SimoneLSK** [ioxe/graphql-aws-iot-example#2]
Hello, 

please feel free to contact me via whatsapp +85298330232

Thanks

**Comment by gnanda17** [comment]
how can I help you?

**Comment by SimoneLSK** [comment]
we would like to have your assistance in setup an IOT with graphql, 
please contact us in person for further discuss

**Comment by gnanda17** [comment]
I do contract work under [IoX Engineering](https://www.linkedin.com/company/iox/)
If you can send me an email at girish@ioxengineering.com with a description of the assistance that is required we could take the conversation further.
